### ISSUE TITLE
No 1080p Audio

### ISSUE THREAD

**Issue by fishcharlie** [fent/node-ytdl#121]
Why does it seem like there is always no audio for the 1080p versions of videos? 720p seems like the highest that includes audio.

**Comment by fent** [comment]
that's how youtube organizes their formats. they have formats with both video and audio, usually the highest at 720p. and then they have separate formats for high bitrate video and audio. youtube plays these together on their website

**Comment by fishcharlie** [comment]
@fent Any tools to combine them locally? I’m assuming I could download the audio and video separately then use a video editing tool to combine them. But anything to do it easier that you are aware of?

**Comment by fent** [comment]
check out [ffmpeg](https://ffmpeg.org/)

there's also [pully](https://github.com/jimbuck/pully), another cli for downloading youtube videos that supports joining formats together
