### ISSUE TITLE
which ip address it will use?

### ISSUE THREAD

**Issue by coolguruji** [fent/node-ytdl#124]
Hi,

If i install it in my server and run it whose ip address its gonna sent to youtube?
I mean server's ip or i can send my users ip address.

I am asking this because currently i was using youtube-dl with php for downloading + converting this videos but from the couple of months i started to get 429 too many requests and ip blocked issue.
right now i cant see any solution so i am looking for a different kind of approach. 
I want to send user's ip to download youtube videos!

Is it possible?

**Comment by fent** [comment]
the server's ip. there's no support for proxy yet
