### ISSUE TITLE
Music info object always empty

### ISSUE THREAD

**Issue by talhabalaj** [fent/node-ytdl#151]
I noticed that `ytdl` doesn't fetch the music information on a song on youtube. It does have an object but it's always empty.

**Comment by RG031102** [comment]
What function are you using as well are you awaiting the function you are using?

**Comment by talhabalaj** [comment]
> What function are you using as well are you awaiting the function you are using?

`ytdl.getInfo(youtubeUrl)` or `ytdl --info-json youtubeUrl`, both return an empty music object

**Comment by fent** [comment]
has been fixed in latest version
