### ISSUE TITLE
Cannot use it on Windows

### ISSUE THREAD

**Issue by chrisvoo** [fent/node-ytdl#155]
Hi,
I tried to simply download only the audio of a video:
```
C:\Users\User>ytdl https://www.youtube.com/watch?v=Wbh2Ce4ZfNY -o herbert.mp4 --filter audioonly
No such format found: highest
```
As far as I know, the `q` parameter has `highest` as default value. Do I lack some dependency? 

* OS: `Windows 10`
* Node version: `v12.13.1`
* ffmpeg: ` git-2019-11-01-53c21c2`
* npm: `6.14.2`

**Comment by fent** [comment]
it's  a bug when using `-o` with a file extension. will fix soon.
