### ISSUE TITLE
Downloaded video file is unplayable

### ISSUE THREAD

**Issue by trnikon** [fent/node-ytdl#156]
Tried downloading a videos with the default options but VLC won't play it and won't show any info about it.

**Comment by fent** [comment]
does this happen for any video tried? does opening the file in a text editor show anything?

**Comment by trnikon** [comment]
It happened for all 3 videos I tried. The file does have some readable data like "ftypmp42" and "isommp42". Vlc tries to seek but eventually stops.

**Comment by trnikon** [comment]
[This ](https://filebin.net/97hb6rg0l2fap86t/test.mp4?t=52caua9q) is the result of running the command on a short test video:

`ytdl "https://www.youtube.com/watch?v=zGDzdps75ns" > test.mp4`

**Comment by fent** [comment]
weird. i'm not able to reproduce after running the above command. :/

and I'm not sure what the binary data in that file is if it's not a valid video file

**Comment by jaromanda** [comment]
The youtube link above by @trnikon works for me ... but, I've found many videos are unplayable when downloaded - all of which can not be played in VLC using youtube URL

two examples:
https://www.youtube.com/watch?v=gopmFUePN4U
https://www.youtube.com/watch?v=uu_EOkyK36Y
