### ISSUE TITLE
Print-url IP Locked

### ISSUE THREAD

**Issue by t3r00t** [fent/node-ytdl#163]
### Hello 

I know this is not a *Bug* but print-url should give an url the API Call that is used to make that final url or something like that.

When node-ytdl is ran on a VPS we cannot use the link and more importanly we cannot share the link with multiple people without downloading it locally then sharing the copy.
Downloading a copy locally will use alot of uneccessary network bandwidth and storage

I know that the generated links have an expire timestamp.

#### Thanks sir !

**Comment by fent** [comment]
the url given is the final url. i've heard that they're not ip locked when using ipv6. i haven't verified that myself, but you could try it.
