### ISSUE TITLE
Everything is webm now

### ISSUE THREAD

**Issue by yocontra** [fent/node-ytdl#34]
It used to be able to grab mp4s for every video, then only some, now none. Probably outside of the scope of the library but you could leverage a ffmpeg binding to transcode on the fly so what YT provides doesn't matter.

**Comment by benbuck** [comment]
Hi @fent,

I found an interesting case:

```
itag container quality codecs                 bitrate  audio bitrate size
 248 webm      1080p   vp9                    2.52MB
  18 mp4       360p    avc1.42001E, mp4a.40.2 397.79KB 96KB          115.72MB
 137 mp4       1080p   avc1.640028            5.03MB                 636.89MB
 134 mp4       360p    avc1.4d401e            788.68KB               92.72MB
 251 webm              opus                            160KB         37.36MB
 140 mp4               mp4a.40.2                       128KB         36.78MB
  22 mp4       720p    avc1.64001F, mp4a.40.2 1.27MB   192KB
 248 webm      1080p   vp9                    2.52MB
 136 mp4       720p    avc1.4d400c            2.2MB
 247 webm      720p    vp9                    1.44MB
 135 mp4       480p    avc1.4d4014            1.1MB
 244 webm      480p    vp9                    735KB
 243 webm      360p    vp9                    396.21KB
 133 mp4       240p    avc1.4d400c            236.33KB
 242 webm      240p    vp9                    215.33KB
 160 mp4       144p    avc1.4d400b            105.47KB
 278 webm      144p    vp9                    92.77KB
```

The highest video resolution (1080p) streams don't have audio. If you don't specify anything, you get the 1080 webm stream with no audio (itag 248). If you filter for mp4, you get the 360p mp4 stream (itag 18) which has both audio and video, but the highest quality mp4 stream with both audio and video is 720p (itag 22). 

I can't really say that the default selection is wrong, but maybe it's worth factoring presence of audio into the quality selection algorithm?

The mp4 filtered selection seems wrong, I can't think of any reason to prefer the 360p stream over the 720p one.

Thanks so much for this tool,
Benbuck
