### ISSUE TITLE
Allow audio download option

### ISSUE THREAD

**Issue by benkaiser** [fent/node-ytdl#37]
I am working on [a music player built with node.js](https://github.com/benkaiser/node-music-player), and one feature I would love to add is an 'add from youtube' button, that allowed the user to download a song from a youtube link into their library.

Would it be possible to add support for downloading of mp3 files?

Thanks for the awesome library!

**Comment by corwin-of-amber** [comment]
In the current state of Youtube, it is in fact possible to download only the audio stream by providing the appropriate ITAG.
```
% ytdl -i 'https://www.youtube.com/watch?v=lCteJY1-Zkk'

title: The Prince of Egypt - 12 - When You Believe
author: Rogue Music Freak
average rating: 4.91761636734
view count: 1765067
length: 4:57
formats:
itag container resolution video enc     audio bitrate audio enc
43   webm      360p       VP8           128           vorbis
18   mp4       360p       H.264         96            aac
36   3gp       240p       MPEG-4 Visual 36            aac
17   3gp       144p       MPEG-4 Visual 24            aac
135  mp4       480p       H.264
244  webm      480p       VP9
134  mp4       360p       H.264
243  webm      360p       VP9
133  mp4       240p       H.264
242  webm      240p       VP9
160  mp4       144p       H.264
278  webm      144p       VP9
251  webm                               160           opus
140  mp4                                128           aac
171  webm                               128           vorbis
250  webm                               70            opus
249  webm                               50            opus
```

To get an audio track, use one of the ITAGs that do not have a video encoder.
E.g.
```
% ytdl 'https://www.youtube.com/watch?v=lCteJY1-Zkk' -q 251 | ffplay -
```
Downloads and plays just the audio.

This could be a nice enhancement to the CLI to provide a flag so that ytdl just skips the tags that have a video stream.

**Comment by fent** [comment]
Sure, that sounds good. I've made a separate issue for it at #56
