### ISSUE TITLE
Can you provide me the simple one page example.

### ISSUE THREAD

**Issue by kapilkarda** [fent/node-ytdl#45]
Hello,
I want a example of that please help me.
Thanks

**Comment by fent** [comment]
https://github.com/fent/node-ytdl#usage

**Comment by kapilkarda** [comment]
could you provide me the working example in javascript ?

**Comment by fent** [comment]
read the top of the readme

**Comment by kapilkarda** [comment]
How can i use this using Ionic. Please Help me sir.

Thanks in Advance. :)

**Comment by fent** [comment]
I don't know
