### ISSUE TITLE
Can't download a video from a list

### ISSUE THREAD

**Issue by jpgtama** [fent/node-ytdl#46]
Dear fent,

I try to download a video with this url: https://www.youtube.com/watch?v=bmE6SWE6c_A&list=PL1A2CSdiySGJ6oZe6XB-TTCFuHc5Fs1PO&index=2, but it failed. The output file has 0 byte.

**Comment by jpgtama** [comment]
And ytdl just dump a lot of stuff to terminal screen.

**Comment by fent** [comment]
What's the command you used? ytdl writes to stdout by default

https://github.com/fent/node-ytdl#usage

**Comment by jpgtama** [comment]
I use below usage:
```
ytdl url > somefile.mp4
```

**Comment by jpgtama** [comment]
I tried to add `-o myfile.mp4` option but the result is the same.

**Comment by fent** [comment]
Did you surround the url in quotes?

**Comment by jpgtama** [comment]
No, I didn't. Just followed your usage which has no quotes. Let me try to surround with quotes.

**Comment by fent** [comment]
In the terminal, characters like & must be escaped.

**Comment by jpgtama** [comment]
Yes, you're right. That's why I found the command was executed in background.

**Comment by jpgtama** [comment]
I surround the url with quotes and it works now. Thanks. :+1:
