### ISSUE TITLE
Error using this plugin

### ISSUE THREAD

**Issue by jwright04** [fent/node-ytdl#47]
Hello, 

I followed the instructions for downloading a video and ended up with an error that resulted in:
```
1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c;1;1;112;112;1;0x1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;2c1;
```
The video never actually downloaded.  Not sure if this is something on my end, but I figured I'd mention this.

**Comment by fent** [comment]
What command did you run exactly? And that was the output?

**Comment by jwright04** [comment]
Sorry @fent major user error, I overlooked the > symbol.
