### ISSUE TITLE
Verbose output

### ISSUE THREAD

**Issue by ivansabik** [fent/node-ytdl#48]
Great script, working fine for me and really easy to get started. Any chance a --verbose mode could be include to see what's going on behind the scenes?

**Comment by fent** [comment]
What would you like to know?

**Comment by ivansabik** [comment]
The download progress mainly but would be nice to see also the URL where
its grabbing it, similar to -i

**Comment by fent** [comment]
The download progress is printed with the `-o` option

**Comment by ivansabik** [comment]
Oh I see, didnt try that
