### ISSUE TITLE
--print-url doesn't work in some videos

### ISSUE THREAD

**Issue by mallendeo** [fent/node-ytdl#49]
I have this problem with a couple of videos

> ytdl --print-url https://www.youtube.com/watch?v=W-MvdWzYr_4 -q 22 

The printed url returns a 403 error

but this command works
> ytdl https://www.youtube.com/watch?v=W-MvdWzYr_4 -q 22 > test.mp4

Since the download option takes the same url, I don't know why it's not working

Thanks

**Comment by kewitz** [comment]
The same happens here. Maybe something to do with the headers?
