### ISSUE TITLE
your caching addition gives errors

### ISSUE THREAD

**Issue by xangadix** [fent/node-ytdl#50]
I see there was an update for caching, last month, but ytdl does no longer work for me now :(

`$ytdl https://www.youtube.com/watch?v=KCxQ3hYHrZk -o yacht_pearl_white.mp4`

gives me: 

```/usr/local/lib/node_modules/ytdl/bin/ytdl.js:101
  var cachefile = path.resolve(os.homedir(), '.ytdl-cache.json');
                                  ^
TypeError: Object #<Object> has no method 'homedir'
    at Object.<anonymous> (/usr/local/lib/node_modules/ytdl/bin/ytdl.js:101:35)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Function.Module.runMain (module.js:490:10)
    at startup (node.js:123:16)
    at node.js:1030:3
```

downgrading to 0.3.5 (before the cache update) now gives me a key error:

```3074569936:error:0607907F:digital envelope routines:EVP_PKEY_get1_RSA:expecting an rsa key:../deps/openssl/openssl/crypto/evp/p_lib.c:288:```

I've tried it both on windows 10 and linux (Debian 6.0.10)

( could be that I'm missing something blatantly obvious )

**Comment by fent** [comment]
Hmm, I think `os.homedir()` was added on node v4. If you can update, try that.

**Comment by xangadix** [comment]
yupyup, that fixed it, thank you.

**Comment by fent** [comment]
Reopening, I'm still planning on supporting the last 2 versions.
