### ISSUE TITLE
Error code 150 - not available in your country strange behavor

### ISSUE THREAD

**Issue by macdja38** [fent/node-ytdl#52]
node-ytdl and ytdl-core seem to be failing at fetching youtube videos that are available in the server's country and can be successfully downloaded using youtube-dl

Tested with:
```
ytdl v2AC41dglnM
```
Which failed with error code: `Code 150: The uploader has not made this video available in your country.`

While testing youtube-dl
```
youtube-dl -v v2AC41dglnM
```
Resulted in no issues.

**Comment by fent** [comment]
Do you have an example of a video not available in the US? Where I am, so I can test.

**Comment by macdja38** [comment]
@fent I wish I did, I was testing in Canada and it was working on my local computer but not the server that's in the same country.

**Comment by icchis** [comment]
I am facing the same problem.
I want to know how to specify the regionCode.

**Comment by DasWolke** [comment]
Same for me with a Server in France

**Comment by DasWolke** [comment]
https://youtube.com/watch?v=-ldQ5RNBvs4
https://youtube.com/watch?v=iCELzsx_59A
https://youtube.com/watch?v=w2xLFIdH9G4
https://youtube.com/watch?v=rZIspmU939o
https://youtube.com/watch?v=d8wBMkvtRaI
https://youtube.com/watch?v=XKSQX2Rn9UM
https://youtube.com/watch?v=xCWTRfQLaGo
https://youtube.com/watch?v=_HsXIvpLdHE
https://youtube.com/watch?v=_c8kpplUkfs
https://youtube.com/watch?v=byPofX1IEZY
https://youtube.com/watch?v=NuAMLQmRnaY
https://youtube.com/watch?v=1hD0OdPDgAE
These Videos returned Code 150 (using ytdl-core & Node v6.9.2) for me.
I will now try it out with normal youtube-dl

**Comment by fent** [comment]
Going to close this here and tracking on https://github.com/fent/node-ytdl-core/issues/90
