### ISSUE TITLE
Default quality is not really highest

### ISSUE THREAD

**Issue by sandman21dan** [fent/node-ytdl#54]
Given a 4k video, for example (https://www.youtube.com/watch?v=p9nqQuu4lmQ)

executing `ytdl https://www.youtube.com/watch?v=p9nqQuu4lmQ -o video.mp4`

does not yield the highest available itag setting for this particular video

**Comment by fent** [comment]
It sorts formats by available video and audio, then by video bitrate, followed by audio bitrate.

So it considers the highest available video quality that also has an audio track what most users would want, as a default.

**Comment by sandman21dan** [comment]
Makes sense, didn't realize >= 720p don't have audio as part of the video file, and matching video and audio would require mixing both files which goes out of the scope of this tool

**Comment by fent** [comment]
It might be something that's added at some point in the future.

[pully](https://github.com/JimmyBoh/pully) already does it.
