### ISSUE TITLE
Create corrupted mp3 file?

### ISSUE THREAD

**Issue by Tuizi** [fent/node-ytdl#58]
What is the correct way to save the video as a .mp3 file?

Try this one:
```ytdl ttps://www.youtube.com/watch?v=_GQW7jqezqA > test.mp3 --filter audioonly```

The output of this command is a corrupted mp3 file. But if I do, ```> test.mp4 --filter audio``` it's perfect

**Comment by fent** [comment]
`mp3` isn't an available format. Use `ytdl -i` to get a list of all formats for a video, there are only `webm` and `mp4` for videos with only audio.

If you absolutely need the file to be an mp3, look at https://github.com/JimmyBoh/pully

**Comment by Tuizi** [comment]
Thank you very much
