### ISSUE TITLE
Add normalized author/title properties for easier downloads

### ISSUE THREAD

**Issue by dadooda** [fent/node-ytdl#68]
Hey Roly,

Enjoying first days with your tool, looks awesome so far.

It would be great if the tool could normalize properties such as `author` and `title` to make them filesystem-friendly. Many YouTube videos have `|` or `:` in their title which is incompatible or awkward with most filesystems.

Implementation may vary, I'd go for something like `--normalize-props` which would enable normalization.

```
$ ytdl -i https://www.youtube.com/watch?v=AbCd1234

title: The quick | brown fox?
author: "The channel": daily <*fun*>
...

$ ytdl -i https://www.youtube.com/watch?v=AbCd1234 --normalize-props

title (normalized): The quick - brown fox
author (normalized): The channel- daily -fun
```

Normalization technique could vary, I'd start with the simplest one first, e.g. this one:

1. Replace all "bad" chars with `-`.
2. Replace 2+ `-` substrings with a single `-`, if any.  
Say, `?"` becomes `--` which then becomes `-`.
3. Remove `-` from head and tail of the string, if any.

For determining which chars are "bad" we'd better stick DOS filesystem rules since they are the most limiting.

Hope that makes sense.

Alex

**Comment by fent** [comment]
Hi, thanks for the suggestion.

I looked this up on SO and I'm leaning towards this solution https://stackoverflow.com/questions/457994/what-characters-should-be-restricted-from-a-unix-file-name/34193591#34193591

**Comment by sparcut** [comment]
@fent [`parshap/node-sanatize-filename`](https://github.com/parshap/node-sanitize-filename) is a super small simple util, looks to have a lot of research behind it, prob better than just a regex.
