### ISSUE TITLE
Make it global stream downloader .

### ISSUE THREAD

**Issue by SalimF** [fent/node-ytdl#72]
I pass on many stram video downloader nclude youtube-dl , but stream sites always change their players video sorces parameters , e.g using Eval etc ..
in short node.JS is javascript based language it will be more suitable to Clone [video.min.js](https://cdnjs.cloudflare.com/ajax/libs/video.js/6.5.0/video.min.js) click event on HTML5 player and detect original video src file similar to web browser . her is [Exanple](https://k-vid.net/load.php?id=MTA0NzQw) to similar players

**Comment by fent** [comment]
If your suggestion is to make ytdl work for any website with videos, it isn't that simple. Every site is different, even slight different, in how they serve videos.

I could see video detection working in the browser level, for like an extension or greasemonkey script. But ytdl-core, and similar modules work without running a browser.
