### ISSUE TITLE
Could not extract signature deciphering actions

### ISSUE THREAD

**Issue by jakeweb** [fent/node-ytdl#81]
Hello, I'm on Windows 10 x64, node -v 8.9.4, npm -v 5.6.0. 
I've been cloned your repository, installed npm modules, ran 

`ytdl http://www.youtube.com/watch?v=_HSylqgVYQI > myvideo.mp4` 

and got error 

`Could not extract signature deciphering actions`
http://prntscr.com/ic8kpt

What is wrong? Thanks

**Comment by fent** [comment]
This was recent but with ytdl-core, make sure it has been updated to its latest version, v0.20.1

**Comment by RobertoMalatesta** [comment]
Same problem with Ubuntu 14.04, node 9.5.0 ytdl@0.10.0 , ytdl-core@0.20.1

--R

**Comment by Kashalls** [comment]
Same as well as @RobertoMalatesta but on Ubuntu 16.04

**Comment by scirahul** [comment]
Same issue on Ubuntu 16.04.2 LTS with latest version, v0.20.1

**Comment by Kashalls** [comment]
Use this solution here: https://github.com/fent/node-ytdl-core/issues/284

**Comment by sr229** [comment]
This seems to affect our clients as well, they always use latest.
