### ISSUE TITLE
Video missing thumbnail

### ISSUE THREAD

**Issue by LevitatingBusinessMan** [fent/node-ytdl#85]
I just had a project of mine crash with this error: https://sharex.reinfernhout.xyz/i/2nTHa.png. For some reason the `getInfo` functions output was missing a thumbnail object.

Is this normal behavior or was this a bug? I have only seen this happen once and I have played thousands of songs[](url)

Sorry for not having any more info about the error, I accidentally cleared the console so I am lucky I made that screenshot

**Comment by fent** [comment]
Do you remember the  video this happened in? It could be that some videos may not have thumbnails, it's pretty common for YouTube to change the metadata ytdl-core gets, since this is from an unofficial API.

**Comment by Gamerein** [comment]
I have no idea on what video it happened. I made a patch that should handle missing data now but before I pushed it the exact same thing happened again. I thought I should let you know, if I am able to get a video url that has this issue I'll let you know
